// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PalmMap.Api.Data;

#nullable disable

namespace PalmMap.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208000000_AddReviewCriteriaRatings")]
    partial class AddReviewCriteriaRatings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PalmMap.Api.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriteriaRatings")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDirectRating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModeratedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModeratorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
